# Generated by Django 5.2 on 2025-04-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary_pl', models.TextField(blank=True)),
                ('summary_en', models.TextField(blank=True)),
                ('summary_it', models.TextField(blank=True)),
                ('summary_de', models.TextField(blank=True)),
                ('summary_fr', models.TextField(blank=True)),
                ('summary_es', models.TextField(blank=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
    ]
