# Generated by Django 5.0.6 on 2025-05-01 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(max_length=250, unique_for_date='date')),
                ('url', models.URLField()),
                ('priority', models.IntegerField()),
                ('summary_pl', models.TextField()),
                ('summary_en', models.TextField()),
                ('summary_it', models.TextField()),
                ('summary_de', models.TextField()),
                ('summary_fr', models.TextField()),
                ('summary_es', models.TextField()),
            ],
            options={
                'ordering': ('priority',),
            },
        ),
    ]
