# Generated by Django 5.0.6 on 2025-05-13 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_task_assigned_to_alter_task_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'ordering': ('-priority',)},
        ),
    ]
